//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_DesignPatter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compte
    {
        public int Id { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string email { get; set; }
        public string motDePasse { get; set; }
        public Nullable<System.DateTime> dateCreation { get; set; }
    }
}
